// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: temperature.proto

package temperature

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TemperatureMonitor_SendTemperature_FullMethodName = "/temperature.TemperatureMonitor/SendTemperature"
)

// TemperatureMonitorClient is the client API for TemperatureMonitor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 溫度監測服務
type TemperatureMonitorClient interface {
	SendTemperature(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TemperatureReading, Ack], error)
}

type temperatureMonitorClient struct {
	cc grpc.ClientConnInterface
}

func NewTemperatureMonitorClient(cc grpc.ClientConnInterface) TemperatureMonitorClient {
	return &temperatureMonitorClient{cc}
}

func (c *temperatureMonitorClient) SendTemperature(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TemperatureReading, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TemperatureMonitor_ServiceDesc.Streams[0], TemperatureMonitor_SendTemperature_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TemperatureReading, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TemperatureMonitor_SendTemperatureClient = grpc.BidiStreamingClient[TemperatureReading, Ack]

// TemperatureMonitorServer is the server API for TemperatureMonitor service.
// All implementations must embed UnimplementedTemperatureMonitorServer
// for forward compatibility.
//
// 溫度監測服務
type TemperatureMonitorServer interface {
	SendTemperature(grpc.BidiStreamingServer[TemperatureReading, Ack]) error
	mustEmbedUnimplementedTemperatureMonitorServer()
}

// UnimplementedTemperatureMonitorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTemperatureMonitorServer struct{}

func (UnimplementedTemperatureMonitorServer) SendTemperature(grpc.BidiStreamingServer[TemperatureReading, Ack]) error {
	return status.Errorf(codes.Unimplemented, "method SendTemperature not implemented")
}
func (UnimplementedTemperatureMonitorServer) mustEmbedUnimplementedTemperatureMonitorServer() {}
func (UnimplementedTemperatureMonitorServer) testEmbeddedByValue()                            {}

// UnsafeTemperatureMonitorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TemperatureMonitorServer will
// result in compilation errors.
type UnsafeTemperatureMonitorServer interface {
	mustEmbedUnimplementedTemperatureMonitorServer()
}

func RegisterTemperatureMonitorServer(s grpc.ServiceRegistrar, srv TemperatureMonitorServer) {
	// If the following call pancis, it indicates UnimplementedTemperatureMonitorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TemperatureMonitor_ServiceDesc, srv)
}

func _TemperatureMonitor_SendTemperature_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TemperatureMonitorServer).SendTemperature(&grpc.GenericServerStream[TemperatureReading, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TemperatureMonitor_SendTemperatureServer = grpc.BidiStreamingServer[TemperatureReading, Ack]

// TemperatureMonitor_ServiceDesc is the grpc.ServiceDesc for TemperatureMonitor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TemperatureMonitor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "temperature.TemperatureMonitor",
	HandlerType: (*TemperatureMonitorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendTemperature",
			Handler:       _TemperatureMonitor_SendTemperature_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "temperature.proto",
}
